### ISSUE TITLE
[Feature Request] Allow drag-and-drop to system tray icon to send file to recycle bin

### ISSUE THREAD

**Issue by jean3x7** [warg0x4e/HotBin#1]
Allow to drop selected itens direct to recycle bin

**Comment by warg0x4e** [comment]
Thank you for the feature request.

It's more efficient to press the delete key, or right-click and select delete, than to drag files and folders to a system tray icon.

**Comment by warg0x4e** [comment]
How about double click to empty but require confirmation (even if Show recycle confirmation is off) to prevent accidental empty?
