### ISSUE TITLE
Run at user logon doesn't work.

### ISSUE THREAD

**Issue by streetwolf** [warg0x4e/HotBin#12]
Running HotBin-2.11.0.0-x64.exe. Even though option is enabled it doesn't show up in the run list. I had to manually add it to my startup folder.

**Comment by warg0x4e** [comment]
Thanks. I've confirmed. I'll have it fixed soon.

You can downgrade to 2.10 until then.

**Comment by warg0x4e** [comment]
https://github.com/warg0x4e/HotBin/releases/tag/2.11.1.0

Before testing, please delete the shortcut you created in the Startup folder.
