### ISSUE TITLE
Enhancement - Swap Left Click and Right Click of Tray Icon

### ISSUE THREAD

**Issue by ghost** [warg0x4e/HotBin#5]
While using HotBin I've noticed that there is no option to change the left click and right commands for the tray. Coming from MiniBin and TrayBin I'm used to having the left click and right click commands reversed. Is there any way we can get an option to swap these commands?

**Comment by warg0x4e** [comment]
Hello, dburow03. I appreciate your feature requests.

I will consider showing the Tray Menu on left-click instead of opening the Recycle Bin on-left click, if possible with AHK.

The lack of configuration and features is intentional. HotBin is simple access to the Recycle Bin from the System Tray.

**Comment by warg0x4e** [comment]
In the next release, left-click and right-click will show menu, middle-click will open the recycle bin folder.

Thank you for your contribution.

**Comment by warg0x4e** [comment]
https://github.com/warg0x4e/HotBin/releases/tag/2.9.0.0
