### ISSUE TITLE
[Feature Request] Double click icon to empty and confirmation bypass

### ISSUE THREAD

**Issue by AlDollaz** [warg0x4e/HotBin#6]
And to possibly bypass the empty confirmation prompt.

Thank you!

**Comment by warg0x4e** [comment]
How about a toggle to enable or disable confirmation, and a bypass by holding Ctrl for when you want to bypass this time but not disable?

I'm reluctant to do a double-click to empty because someone out there is going to empty their Recycle Bin accidentally. Convince me?

**Comment by AlDollaz** [comment]
How about an option to enable double click to empty? But off by default. Same with disable confirmation. If you've ever used MiniBin, those options are there. 😊

(sure I could use MiniBin, but it's old and hasn't been worked on in years)

**Comment by warg0x4e** [comment]
The overwhelming difficulty I have in adding new features to HotBin is that I use multilingual strings provided by Windows.

The strings seen in the tray menu are string resources from dlls that have native language support.

The intention was support any language that Windows supports. HotBin was intended to be just a simple tray icon for the Recycle Bin, not needing any strings not already available.

For example, "Run at user logon" is a string provided by mstask.dll. it's in English for English, Japanese for Japanese, Arabic for Arabic, etc.

By this design, adding new settings to the tray menu requires strings being available in Windows that makes sense for the feature.

This is a limitation, I know, but again, HotBin was never intended to be feature-rich, or a replacement for MiniBin or similar.

If can't find multilingual strings for a feature, then the feature can't be on the tray menu.

This isn't a no, but a we'll see how it works out.

**Comment by AlDollaz** [comment]
Fair enough, thanks for the consideration. 👍🏻

**Comment by warg0x4e** [comment]
Show recycle confirmation is a yes.

![ar-SA](https://github.com/warg0x4e/HotBin/assets/2155010/2523c67a-6ffd-4720-b506-f65238e64cce)
![en-US](https://github.com/warg0x4e/HotBin/assets/2155010/f5fa706a-917b-4df2-bbe3-a396fd7cf396)

**Comment by warg0x4e** [comment]
https://github.com/warg0x4e/HotBin/releases/tag/2.9.2.0

**Comment by warg0x4e** [comment]
https://github.com/warg0x4e/HotBin/releases/tag/2.9.3.0

**Comment by warg0x4e** [comment]
https://github.com/warg0x4e/HotBin/releases/tag/2.9.3.0

**Comment by AlDollaz** [comment]
Perfect! Absolutely perfect! Thank you so much!

Do you have a donation link? I'd love to contribute for your work.

**Comment by warg0x4e** [comment]
I do not, but thank you.
